<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Syrnik\\' => array($vendorDir . '/syrnik/wa-shipping-utils/src'),
    'SergeR\\Util\\EvalMath\\' => array($vendorDir . '/serger/eval-math/src'),
    'SergeR\\CakeUtility\\' => array($vendorDir . '/serger/cake-utility/src'),
);
