<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4d0c7bed7569f16832aad3db9cc55c88
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Syrnik\\' => 7,
            'SergeR\\Util\\EvalMath\\' => 21,
            'SergeR\\CakeUtility\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Syrnik\\' => 
        array (
            0 => __DIR__ . '/..' . '/syrnik/wa-shipping-utils/src',
        ),
        'SergeR\\Util\\EvalMath\\' => 
        array (
            0 => __DIR__ . '/..' . '/serger/eval-math/src',
        ),
        'SergeR\\CakeUtility\\' => 
        array (
            0 => __DIR__ . '/..' . '/serger/cake-utility/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4d0c7bed7569f16832aad3db9cc55c88::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4d0c7bed7569f16832aad3db9cc55c88::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
