<?php return array(
    'root' => array(
        'name' => 'syrnik/shipping-nrg',
        'pretty_version' => '2.0.0',
        'version' => '2.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'serger/eval-math' => array(
            'pretty_version' => 'v2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'ce8d7503de4cbff339be33d5bb8bd6f589988b39',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serger/eval-math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'syrnik/shipping-nrg' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'syrnik/wa-shipping-utils' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '80da76cb0f8cdc4582f6be3a5230f352286116d4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../syrnik/wa-shipping-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
