<?php return array(
    'root' => array(
        'name' => 'syrnik/shipping-nrg',
        'pretty_version' => 'dev-develop',
        'version' => 'dev-develop',
        'reference' => '10008b3b65290fadb291c55b1c3a684c66d11c01',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'serger/cake-utility' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'c7d6554c08f1d93be9f3f4b1c5cae10733558d42',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serger/cake-utility',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'serger/eval-math' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'a9eae61df21bd19f693f78261f40a705f0551232',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serger/eval-math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'syrnik/shipping-nrg' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'reference' => '10008b3b65290fadb291c55b1c3a684c66d11c01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'syrnik/wa-shipping-utils' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'da8337d3bbbe1ae4072dc204c41e033f144a84ab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../syrnik/wa-shipping-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
